### ISSUE TITLE
Compiler in Makefile hardcoded to "icpc"

### ISSUE THREAD

**Issue by lbeltrame** [fukunagatsu/RIblast#1]
At a quick glance, the compiler is hardcoded (the Intel compiler). This is rarer to find in "regular" distribution installations, so it should default to the system compiler, or to what the user specifies.

A solution would be to use  the implicit variable   `$(CC)` in the `Makefile`.

**Comment by fukunagatsu** [comment]
Thank you for your comments.
I revised my makefile to a suitable file for the distribution.
