### ISSUE TITLE
command RIblast

### ISSUE THREAD

**Issue by julierodor** [fukunagatsu/RIblast#11]
Hi,

I don't have much experience on installing new tools so if you could help me, that would be nice.

I have used this command to download the sofware
git clone https://github.com /fukunagatsu/RIblast.git
It created the folder RIblast with all the different files such as db_construction.cpp
I cannot use ./RIblast db as RIblast is directory and there is no RIblast file inside the RIblast folder
Is there anything I have to do?

You also mention the BL* energy model. Do I need to install/download this model?
Any help would be greatly appreciated.

Julie

**Comment by fukunagatsu** [comment]
I apologize for my late reply. Thank you for your interest in my software.

You have to compile RIblast software from our source code. To be more specific, you have to type "make" in RIblast directory, and then RIblast software will be created.

You do not need to install BL* energy model because this model has already been incorporated into the software.

Best,
Tsukasa

**Comment by julierodor** [comment]
Thanks very much for your help.
I did 'make' and I tried to create the database and checking interaction but I end up with an empty output.
Do you mind telling me if the commands below are correct?

I want to compare the interaction between the lncRNA SMILR (sequence_hSMILR_RACE_formatted.fa) and some mRNA targets (sequences_transcripts_DGE_SMILR_FPKM_SingleId_formatted.fa).
The sequences have been formatted with fasta_formatter -w 0

# database for the mRNA targets => it created several _bd files (.acc, .bas,...)
./scripts/RIblast/RIblast db -i SMILR_interaction/sequences_transcripts_DGE_SMILR_FPKM_SingleId_formatted.fa -o SMILR_interaction/transcripts_DGE_SMILR_RIblast_db

# checking interaction
./scripts/RIblast/RIblast ris -i SMILR_interaction/sequence_hSMILR_RACE_formatted.fa -o SMILR_interaction/output_RIblast_SMILR_default.txt -d SMILR_interaction/transcripts_DGE_SMILR_RIblast_db
# the output does not contain any interaction

Am I doing anything wrong?

Julie


Julie Rodor

Centre for Cardiovascular Science

University of Edinburgh

Queen’s Medical Research Institute

47 Little France Crescent

EH16 4TJ, Edinburgh UK

tel: +44 (0)131  242 6745


________________________________
