### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by wmj002** [fukunagatsu/RIblast#12]
I have tried `sudo make` to install **RIblast-1.1.3** but it returns the following error:

> g++ -O3 -o RIblast main.cpp db_construction_parameters.cpp fastafile_reader.cpp db_construction.cpp encoder.cpp raccess.cpp rna_interaction_search.cpp rna_interaction_search_parameters.cpp ungapped_extension.cpp seed_search.cpp gapped_extension.cpp -x c sais.c
> make: g++: Command not found
> make: *** [Makefile:5: RIblast] Error 127

Could you kindly help with the installation?
Thanks in advance.

**Comment by fukunagatsu** [comment]
Firstly, you have to install g++ compiler into your computer.

**Comment by wmj002** [comment]
Solved!
installing only gcc package didn't work. And I wasn't finding g++ easily.
g++ package has a very unusual name 'gcc-c++'!
Thanks anyway!
