### ISSUE TITLE
std::bad_alloc

### ISSUE THREAD

**Issue by bpucker** [fukunagatsu/RIblast#16]
Hi all,

RIblast looks like a promising tool for one of my projects. Therefore, I was really sad when encountering the following error today:

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

The construction of the database worked fine, but when running the actual search this error appears after a few seconds. As this error message is not very specific, I have no idea how to address this issue. The version is 1.0 and it is running on a LINUX system. Your help would be appreciated.

Thanks,
Boas

**Comment by fukunagatsu** [comment]
Hi Boas,

When there are too many sequences in the database, RIblast output the error message due to lack of memory.
Please run again after reducing the number of sequences in the database.

Best Regards,
Tsukasa

**Comment by bpucker** [comment]
Hi Tsukasa,

Thank you very much for your quick reply. Could you please give me an estimation how many sequences are allowed in the database? Currently, I have about 30,000 sequences in the database.

Thanks,
Boas

**Comment by fukunagatsu** [comment]
Hi Boas,

Depending on the computing environment or the sequence lengths, we keep the number of sequences in a database to about 500-1000.

Best,
Tsukasa
