### ISSUE TITLE
Fatal error: Some files can't be processed by RIblast with throwing exceptions. 

### ISSUE THREAD

**Issue by heartsh** [fukunagatsu/RIblast#5]
When comprehensive analysis has done, some input files (22 over 1524) can't be processed by RIblast with a option, "ris". 
All the exception messages are the same: 
"terminate called after throwing an instance of 'std::out_of_range'
what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 1)".

The input files' names are not problems because when I changed the  name of one of them into 
another such as "hoge.fa" and processed it in the same command, but it failed. 
And the input seq. length seems to be not a problem because one containing longer seq. length has been processed properly. 

The problem should be debugged by a debugger such as GDB. 
But the debug could be difficult without the fatal cases, so I uploaded them (the input files, the database) into my temporary repo (https://github.com/heartsh/riblast-ftl-css). 
The command options should be default ones.

**Comment by fukunagatsu** [comment]
Thank you for your bug report.
I fixed your bug and updated RIblast version.
