### ISSUE TITLE
RIblast has limits to RNA size?

### ISSUE THREAD

**Issue by zhangjunpeng411** [fukunagatsu/RIblast#8]
IntaRNA requires the RNA size <2 kb, RactIP limits the max RNA size to 1 kb, and the RNA size for RNAup is not bigger than 5 kb. Is there any limits of RNA size for RIblast? If so, what is the size of limited RNA size? Thanks for your great work.

**Comment by fukunagatsu** [comment]
RIblast has no limit size for sequence length. Of course, the required memory size for interation prediction is increased in accordance with the sequence length and the number of sequence.

**Comment by fukunagatsu** [comment]
Thank you for your comments. We have already conducted whole human RNA-RNA interaction using RIblast in preparation for the database release. However, it is difficult to set the link to download all predicted interaction because the data size is quite large.

**Comment by zhangjunpeng411** [comment]
It is great. When you have finished the database release using RIblast, would you please let me know? We can cite your work reasonably. Thanks in advance.
